config/routes.rb
Rails.application.routes.draw do

  root to: 'videos#index'

  resources :videos, only: [:index, :show]

  get 'about', to: 'pages#about'

  post 'share_cookies', to: 'videos#share_cookies'
  post 'vote', to: 'votes#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/video.rb
class Video < ApplicationRecord

  validates_uniqueness_of :youtube_id

  has_many :votes, dependent: :destroy

end

app/models/vote.rb
class Vote < ApplicationRecord

  belongs_to :video

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos   = Video.where(published_at: helpers.last_week)
    @featured = Video.where(is_featured: true)
      .order(updated_at: :desc).limit(1).first

    if @featured.blank?
      @featured = Video.order(view_count: :desc).limit(1).first
    end

    if cookies[:apple]
      user = cookies[:apple]
      vote = Vote.where user_id: user, created_at: helpers.this_week
      @chosen_one = vote.last.try :video
    end

    @cookies_ok = cookies[:banana]
  end

  def show
    @video = Video.find params[:id]
    render @video
  end

  def share_cookies
    cookies[:banana] = true
    render partial: 'hide_cookies'
  end

end

app/controllers/votes_controller.rb
require 'securerandom'

class VotesController < ApplicationController

  def create
    if cookies[:apple]
      user = cookies[:apple]
      vote = Vote.where user_id: user, created_at: helpers.this_week
      vote.first.try :destroy
    else
      cookies[:apple] = SecureRandom.uuid
    end

    vote = Vote.create({
      user_id: cookies[:apple],
      video_id: params[:video]
    })

    render vote
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def last_week
    start_of_week = Date.today.last_week.beginning_of_day
    end_of_week   = start_of_week + 1.week

    start_of_week..end_of_week
  end

  def this_week
    start_of_week = Date.today.beginning_of_week.beginning_of_day
    end_of_week   = start_of_week + 1.week

    start_of_week..end_of_week
  end

end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %title Fruit Nation
    %meta{ name: 'Description', content: 'Features the fan favorite Mr. Fruit video as chosen by the community every week.' }
    %link{ href: "https://fonts.googleapis.com/css?family=Open+Sans|Open+Sans+Condensed:700", rel: "stylesheet" }
    = csrf_meta_tags
    = favicon_link_tag 'favicon.png'

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    .container
      = render 'partials/header'
      = yield
      = render 'partials/footer'

    .overlay
      .close.fa.fa-times
      .modal

app/views/pages/about.haml
%ul.scene
  %li.layer{ data: { depth: '1' }}= image_tag 'banner.jpg'

.content
  %h1 The Story of the Fruit

  .baby.photo
    .caption Earliest known photo of Mr. Fruit
    = image_tag 'fruit-baby.png'

  %p
    Mr. Fruit is a gaming sensation that inspires his loyal and Fruity followers. This is the short, thrilling, and 100% accurate tale of how he came to be the Fruit we all know and love today. If you'd rather get right to the good stuff, head on over to his
    = link_to 'YouTube channel', 'https://www.youtube.com/user/MyMisterFruit', target: '_blank'
    , for the latest and greatest of Fruity wonder.

  %p From a very young age, Mr. Fruit was loved by everyone around him. Even in the oldest of photos, he is shown surrounded by friends and family. They were always very supportive of him and all of his endeavors, which is quite fortunate because they were many.

  .campaign.photo.alt.small
    .caption Fruit's Campaign Poster
    = image_tag 'fruit-campaign.png'

  %p
    Like many other great minds of our time, Fruit always believed his future lay outside the world of academic achievement. He tried a plethora of things while growing up, and after many
    %span{ title: 'complete failures' } "near" successes
    , he found he had a knack for politics. And so, Mr. Fruit set off on a long and epic campaign trail.

  %p At first, the people were shocked, more than anything else. They had never seen such political prowess as displayed by Fruit and his crack campaign team. The videos and posters released to the public had a truly awe-inspiring effect — the likes of which have not been seen before or since. Sadly, the bright and Fruity future that lay ahead was cut short when it became clear the world was not yet ready for such greatness.

  .model.photo
    .caption Mr. Fruit in his Modeling Prime
    = image_tag 'fruit-model-car.png'

  %p Picking up the pieces from the shambles of yet another near success, Fruit marched on. After some careful examination and observation, he decided to do the only sensible thing a person could do. He pivoted career paths and barrelled, head-first, into the modeling industry.

  %p For some reason still unknown to this day, he only ever wanted to be a car model. More specifically, a van model. He spent some time doing various high profile gigs around the world, always with different and increasingly exotic vans. Just when it seemed Fruit would live happily ever after in his new profession, the industry began to shut him out. It seemed that they too were not ready such Fruity splendor.

  %p
    At this point, Fruit was running out of ideas. One day, while he was at home recuperating, he recorded himself playing a video game merely on a whim. He put the video on something called YouTube, and was astonished at the
    %span{ title: 'years of hard work and determination' } near instant
    fame and success. Since then, he has continued making videos, finding it to be the
    %span{ title: 'hardest and most demanding' } easiest
    and most rewarding thing he'd ever put his mind to. Finally, Mr. Fruit was happy and content.

  %h2 So On and So Forth

  .dream.photo.alt.small
    .caption The Dream Team
    = image_tag 'fruit-dream.jpg'

  %p
    Mr. Fruit also commonly games with his two buds,
    = link_to 'BlueWestlo', 'https://www.youtube.com/user/bluewestlo', target: '_blank'
    and&nbsp;
    %span>= link_to 'Rhabby V', 'https://www.youtube.com/user/ilovemlg1/videos', target: '_blank'
    \. Blue is known for his resourcefulness, common sense, and rugged good looks. Rob is known for his exorbitant death count, wonderful attitude, and keeping the chaos meter high. Fruit is the glue that holds this epic and dreamy fruit cake together. He is outgoing, goofy, and supremly handy with firearms. This handsome and talented trio is known to the community as "The Dream Team".

  %p In all seriousness, Mr. Fruit is one of the kindest, most genuine, and most unique souls in the gaming community. He consistently provides us with incredible and enjoyable content to detox from the harshness of the world. He inspires us to be passionate and keep our chins up in the face of any and all adversity. He makes each day just a little bit brighter, and we thank him for it.

:javascript
  $('.scene').parallax()

app/views/partials/_footer.haml
%footer
  .wrapper
    %h1 Find the Fruit
    %nav
      = link_to '', 'https://www.youtube.com/user/MyMisterFruit', target: '_blank', class: 'fa fa-youtube'
      = link_to '', 'https://twitter.com/mrfruityt', target: '_blank', class: 'fa fa-twitter'
      = link_to '', 'https://www.instagram.com/MrFruitGaming/', target: '_blank', class: 'fa fa-instagram'
      = link_to '', 'https://www.twitch.tv/mymisterfruit', target: '_blank', class: 'fa fa-twitch'

app/views/partials/_header.haml
%header
  .wrapper
    %h1= link_to 'Fruit Nation', root_path
    %nav
      %div= link_to_unless_current 'Home', root_path
      %div= link_to_unless_current 'About the Fruit', about_path

app/views/videos/_hide_cookies.js.haml
:plain
  $('.cookies').addClass('hide')

app/views/videos/_video.js.haml
:plain
  $('body')
    .addClass('watching').find('.modal')
    .append("#{escape_javascript(@video.embed_html)}")

app/views/videos/index.haml
.featured
  .wrapper
    %h1 Fruity Pick f the Week
    %p
      Every week the community contemplates, deliberates, and after much
      consideration, they cast their vote. The video you see featured here
      is the best of the best. The cream of the crop. The pièce de résistance!

    = raw @featured.embed_html
    - if @featured.description.present?
      %p.description= @featured.description

  %ul.scene
    %li.layer{ data: { depth: '1' }}= image_tag 'background.jpg'

.weekly-videos
  .wrapper
    %h1 Cast your Vote!
    %p
      Each person gets one vote. In the list below, click on your favorite
      video. The video with the most votes will be the featured video next week.

    .videos
      - @videos.each do |video|
        .video[video]{ class: ('chosen' if video.id == @chosen_one.try(:id)) }
          = link_to 'vote', method: 'post', remote: true, data: { params: { video: video.id }.to_param }, class: 'vote' do
            = image_tag video.thumbnail_url

          = link_to 'watch', video_path(video), remote: true, class: 'watch'

    %p.votification-notice Your vote has so totally been saved.

.highlighted-section
  .wrapper
    %p
      Check back each week to cast your vote on new videos. The list is
      refreshed every Monday morning and will include the previous week's
      videos.

- unless @cookies_ok
  .cookies
    = link_to 'close', 'share_cookies', remote: true, method: 'post', class: 'close'
    .wrapper
      %p By continuing to use this site, you agree to share your cookies.

  = link_to 'http://icecreamsandwichcomics.com/post/157923361474/you-are-only-making-him-more-powerful-full-image', target: '_blank', class: 'fool' do
    = image_tag 'fool.png'

:javascript
  $('.scene').parallax()

app/views/votes/_vote.js.haml
:plain

  $("#video_#{vote.video_id}").addClass('chosen')
    .siblings('.video').removeClass('chosen');

  var $notice = $('.votification-notice');
  var showNotice = function() {
    $notice.addClass('animate');
    clearTimeout(window.voting);

    window.voting = setTimeout(function() {
      $('.votification-notice').removeClass('animate');
    }, 3000);
  };

  // If the notice was already showing, hide it.
  // Restart hide timer when the notice is finished hiding.
  if ($notice.hasClass('animate')){
    $notice.removeClass('animate');

    var timing = parseFloat($notice.css('transition-duration')) * 1000;
    setTimeout(showNotice, timing);

  // If the notice was already hidden, show it and start the timer.
  } else {
    showNotice();
  }